from selenium import webdriver


driver = webdriver.Chrome()
driver.get("https://web.whatsapp.com/")
driver.maximize_window()

name1 = input("Enter Contact 1:")
name2 = input("Enter Contact 2:")
gname = input("Enter Group Name:")
number=input('How many group:')
x=int(number)
input("Press Enter after scan QR code")
for x in range(1,x):
    menu=driver.find_element_by_xpath('//*[@id="side"]/header/div[2]/div/span/div[3]/div/span')
    menu.click()
    creategroup=driver.find_element_by_xpath('//*[@id="side"]/header/div[2]/div/span/div[3]/span/div/ul/li[1]/div')
    creategroup.click()
    cont1=driver.find_element_by_xpath('//*[@id="app"]/div/div/div[2]/div[1]/span/div/span/div/div/div[1]/div/div/input')
    cont1.send_keys(name1)
    result=driver.find_element_by_xpath('//*[@id="app"]/div/div/div[2]/div[1]/span/div/span/div/div/div[2]/div[1]/div/div/div/div/div/div[2]')
    result.click()
    cont2=driver.find_element_by_xpath('//*[@id="app"]/div/div/div[2]/div[1]/span/div/span/div/div/div[1]/div/div/input')
    cont2.send_keys(name2)
    result=driver.find_element_by_xpath('//*[@id="app"]/div/div/div[2]/div[1]/span/div/span/div/div/div[2]/div[1]/div/div/div/div/div/div[2]')
    result.click()
    creategroup=driver.find_element_by_xpath('//*[@id="app"]/div/div/div[2]/div[1]/span/div/span/div/div/span/div')
    creategroup.click()
    groupsubject=driver.find_element_by_xpath('//*[@id="app"]/div/div/div[2]/div[1]/span/div/span/div/div/div[2]/div/div[2]/div/div[2]')
    n=(f'{x:03}')
    groupsubject.send_keys(gname+n)
    finalOk=driver.find_element_by_xpath('//*[@id="app"]/div/div/div[2]/div[1]/span/div/span/div/div/span/div/div')
    finalOk.click()
   
    #time.sleep(5)
    #grouptouch=driver.find_element_by_xpath('//*[@id="main"]/header/div[1]/div/div')
    #grouptouch.click()
    #dropadmin=driver.find_element_by_xpath('//*[@id="app"]/div/div/div[2]/div[3]/span/div/span/div/div/div[1]/div[5]/div[4]/div/div[2]/div/div/div[2]/div[2]/div[2]')
    #dropadmin.click()
    #makeadmin=driver.find_element_by_xpath('//*[@id="app"]/div/span[4]/div/ul/li[1]/div')
    #makeadmin.click()
print("Success")